"""Run lifecycle: upload a file, start a run (background job), read back
whatever artifact the pipeline wrote for it. No business logic here - every
handler is a thin read of a JSON artifact or a call into pipeline.runner.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile

from dq_framework.core.config import AppConfig, ModuleRegistry
from dq_framework.pipeline.runner import run

from backend.app.deps import get_app_config, get_job_runner, get_module_registry
from backend.app.jobs.inprocess_runner import InProcessJobRunner
from backend.app.schemas import RunRequest

router = APIRouter(prefix="/api", tags=["runs"])


def _run_dir(app_config: AppConfig, run_id: str):
    return app_config.paths.artifacts_root / "runs" / run_id


def _read_json_artifact(app_config: AppConfig, run_id: str, filename: str) -> dict:
    path = _run_dir(app_config, run_id) / filename
    if not path.exists():
        raise HTTPException(404, f"'{filename}' not found for run '{run_id}' (not generated by this run, or run_id is wrong)")
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("/modules")
def list_modules(registry: ModuleRegistry = Depends(get_module_registry)):
    return [
        {"name": m.name, "description": m.description, "primary_key": m.primary_key, "trigger_modes": m.trigger.modes}
        for m in registry.list()
    ]


@router.get("/runs")
def list_runs(module: str | None = None, app_config: AppConfig = Depends(get_app_config)):
    """Scans artifacts/runs/*/run_metadata.json - the filesystem is the
    source of truth (no DB), so listing runs means listing that directory."""
    runs_root = app_config.paths.artifacts_root / "runs"
    if not runs_root.exists():
        return []
    summaries = []
    for run_dir in sorted(runs_root.iterdir(), reverse=True):
        metadata_path = run_dir / "run_metadata.json"
        if not metadata_path.exists():
            continue
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        if module and metadata.get("module") != module:
            continue
        summaries.append(metadata)
    return summaries


@router.post("/modules/{module_name}/upload")
async def upload_file(
    module_name: str,
    file: UploadFile = File(...),
    registry: ModuleRegistry = Depends(get_module_registry),
    app_config: AppConfig = Depends(get_app_config),
):
    module = registry.get(module_name)
    project_root = app_config.paths.modules_root.parent
    dest_dir = project_root / module.source.incoming_path
    dest_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    dest_path = dest_dir / f"{ts}__{file.filename}"
    dest_path.write_bytes(await file.read())

    return {"source_ref": str(dest_path.relative_to(project_root))}


@router.post("/modules/{module_name}/runs")
def start_run(
    module_name: str,
    body: RunRequest | None = None,
    registry: ModuleRegistry = Depends(get_module_registry),
    app_config: AppConfig = Depends(get_app_config),
    job_runner: InProcessJobRunner = Depends(get_job_runner),
):
    registry.get(module_name)  # 404s early via ModuleNotFoundError_ if the module doesn't exist
    source_ref = body.source_ref if body else None
    job_id = job_runner.submit(run, module_name, source_ref, app_config)
    return {"job_id": job_id}


@router.get("/runs/{run_id}")
def get_run(run_id: str, app_config: AppConfig = Depends(get_app_config)):
    return _read_json_artifact(app_config, run_id, "run_metadata.json")


@router.get("/runs/{run_id}/failures")
def get_run_failures(run_id: str, app_config: AppConfig = Depends(get_app_config)):
    return _read_json_artifact(app_config, run_id, "failure_report.json")


@router.get("/runs/{run_id}/rca")
def get_run_rca(run_id: str, app_config: AppConfig = Depends(get_app_config)):
    return _read_json_artifact(app_config, run_id, "rca_report.json")


@router.get("/runs/{run_id}/compare")
def get_run_compare(run_id: str, app_config: AppConfig = Depends(get_app_config)):
    """Before/after: the raw validation result vs. the post-remediation
    (and, if any candidate has since been approved, post-approval) result."""
    run_dir = _run_dir(app_config, run_id)
    before = json.loads((run_dir / "failure_report.json").read_text(encoding="utf-8"))
    after_path = run_dir / "post_approval_result.json"
    if not after_path.exists():
        after_path = run_dir / "post_remediation_result.json"
    after = json.loads(after_path.read_text(encoding="utf-8")) if after_path.exists() else None

    return {
        "run_id": run_id,
        "before": {"success": before["success"], "failed_expectations": len(before["failures"])},
        "after": after,
    }
